### ISSUE TITLE
CI is failing

### ISSUE THREAD

**Issue by fregante** [sindresorhus/is-stream#18]
It never passed: https://github.com/sindresorhus/is-stream/actions

cc @Richienb

**Comment by Richienb** [comment]
Because the logs have expired, I'm not quite sure what happened here. Would it be possible for the most recent build to be re-run?

**Comment by fregante** [comment]
Probably by opening another PR. I saw the same thing on lot of Sindre’s repo, probably because CI did not run in the original PR and it was forgotten after it was merged.

**Comment by fregante** [comment]
Like 

https://github.com/sindresorhus/broccoli-strip-json-comments
https://github.com/sindresorhus/is-supported-regexp-flag
https://github.com/sindresorhus/macos-version-cli
https://github.com/sindresorhus/gulp-chown

etc, from https://github.com/search?o=asc&p=6&q=user%3Asindresorhus+%22Move+to+GitHub+Actions%22+in%3Atitle&s=created&type=Issues

**Comment by Richienb** [comment]
Does a re-run button exist for you on [this job](https://github.com/sindresorhus/is-stream/actions/runs/505807861)?

![Re-run all jobs](https://user-images.githubusercontent.com/29491356/126759932-145844c4-c587-4436-86e2-1b410597c42e.png)

**Comment by sindresorhus** [comment]
This is now fixed.

@fregante I intentionally did not bother to fix many of the ones that failed in the GitHub Actions migration as I will rewrite them in ESM this year anyway. They'll all be fixed soon.
