### ISSUE TITLE
depending on definition of writable stream

### ISSUE THREAD

**Issue by ORESoftware** [sindresorhus/is-stream#7]
there is a check for a writable stream

```js
isStream.writable = function (stream) {
    return  stream.writable !== false && typeof stream._write === 'function' && typeof stream._writableState === 'object';
};
```

if you do this:

   ```js
        const z = fs.createWriteStream(dest);
        z.write('summa');
        z.end();
        return z;
```

calling `end()` will set writable to false, but it's still a writable stream, it's just no longer writable.

do you think this is a bug or is this the desired behavior? I think it would be better to remove that check to see if writable !==false...

**Comment by ORESoftware** [comment]
then again, if end is called, you may not be able to listen to events because all the events may have already fired, kind of a weird one.

**Comment by kevva** [comment]
This was added due to https://github.com/sindresorhus/is-stream/pull/1. And yeah, technically, it's not a writable stream anymore since you can't write to it.

**Comment by ehmicky** [comment]
I have opened #20 which fixes this.
