### ISSUE TITLE
isStream.writable() returns false for http.ServerResponse

### ISSUE THREAD

**Issue by palanik** [sindresorhus/is-stream#8]
`http.ServerResponse` object is identified as a stream, but not as a writable stream.

`isStream(res)` => returns `true`
`isStream.writable(res)` => returns `false`

Something to note in node [docs](https://nodejs.org/api/http.html#http_class_http_serverresponse):
> The response implements, but does not inherit from, the Writable Stream interface.

Should alternative checks required to detect `http.ServerResponse` as a writable stream? 

PS: request is fine. `isStream.readable(req)` returns `true` for request object.

**Comment by sindresorhus** [comment]
I'm curious why it doesn't inherit from Writable Stream.

@mcollina @jasnell Any insight?

**Comment by mcollina** [comment]
Because it is not a Writable for performance reasons. Otherwise we would have double buffering before hitting the socket, which will slow things down significantly.

I hope it's clear. Probably the docs are not clear on this regard.

**Comment by sindresorhus** [comment]
@mcollina Could you maybe use `Symbol.species` in `http.ServerResponse` to pretend you're inheriting from `stream.Writable`?

**Comment by mcollina** [comment]
Yes we can and it's a gread idea. I'll fire a PR tomorrow.

However there are a couple of problems with this: the first is that it does not implement 100% of the API, i.e. cork() and uncork().

**Comment by mcollina** [comment]
@sindresorhus here it is. Please check https://github.com/nodejs/node/pull/11878.

**Comment by mcollina** [comment]
To clarify, the above will not change the fact that `isStream.writable`  will keep returning `false`, because it's also checking about `_write()`.

**Comment by Qard** [comment]
This still seems to be an issue. Rather than checking for stream internals, would it not be better to check it has the necessary external interface functions? (write, end, etc.)

**Comment by ehmicky** [comment]
Fixed by #21.
