### ISSUE TITLE
request() detected as a stream but does not belong to any of the four stream types

### ISSUE THREAD

**Issue by ghost** [sindresorhus/is-stream#9]
Hello,

```
const request = require('request');
const isStream = require('is-stream');

console.log(isStream(request(`https://google.com`)));  // true
console.log(isStream.readable(request(`https://google.com`))); // false
console.log(isStream.writable(request(`https://google.com`))); // false
```

I'm not sure whether the problem is from 'is-stream' or from the stream library utilization within 'request'.
The check fail because there is no _write() or _writableState object within the function request but the stream is still readable/writable.

Any insight about it ?

**Comment by sindresorhus** [comment]
It might be because `request` is not using Streams v3.

**Comment by sindresorhus** [comment]
Closing as `request` is deprecated, so not worth spending time on looking into this.
